### ISSUE TITLE
Module#2 210817 할 일

### ISSUE THREAD

**Issue by vvonha** [WonhaWoo/NaverAPI#9]
0.
어제 잠깐 얘기했던 내용 중에.. 
nginx를 왜 사용해야 하는 지에 대한 대답
출처 : https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=shino1025&logNo=221364012478
읽어보면 알겠지만
flask로 실행하면 서버 구축한 것처럼 보일 수 있지만
실제로는 서버로 사용하지 말라고 Warning 메세지 뜬다.
즉 nginx를 웹 서버로 사용하고, flask는 프레임 워크로 사용해야지
잘 작동되는 것처럼 보인다고 해서 flask만 사용해도 된다는 게 아님

1.
uWSGI 프로토콜 사용해서 nginx <-> flask 연동 테스트
우원하 : flask에 matplotlib 연동해서 그래프, 이미지 띄우기
조상우 : flask측 uWSGI 연구
강경문 : 도커 컨테이너끼리 네트워킹 연구.. 인터넷 보면 ifconfig 했을때 docker0 라는 bridge가 보인다는데 난 안보임.. 조사 부탁
김민지 : nginx측 uWSGI 연구

화이팅!

**Comment by 2018111320** [comment]
0-2. 
+ 추가(flask만 사용 vs flask + nginx 사용)

1) Flask를 단독 웹서버를 사용하는 법. 
2) 기존 웹서버 (apapache, nginx)에 Flask 서버를 추가하는 방법. 

작동방식을 간단히 정리하면 이와같다.
1)번의 경우 : [요청] -> 웹서버(flask) -> 프로그램 실행 -> 결과리턴 
2)번의 경우 : [요청] -> 웹서버 (Nginx) -> 어플리케이션 서버(flask) -> 프로그램 실행 -> 결과리턴 (역순) 

두 방식의 차이는 Flask를 단독으로 사용 하느냐, 기존 웹서버의 어플리케이션 서버로 연결해서 사용하느냐의 차이이다.

[참고] https://art-it.tistory.com/13
